### ISSUE TITLE
Script Broken 

### ISSUE THREAD

**Issue by baderj** [neurobin/lcget#2]
I followed the install instructions on Ubuntu 16.04. The script `lcget 0.0.3` does not work with `letsencrypt 0.4.1` and  `jssh 0.0.2`. It passes the parameters of the jssh config to letsencrypt, which are not recognized. 

```
$ lcget certonly -c ~/.neurobin/jssh/test.conf 
usage: 
  letsencrypt [SUBCOMMAND] [options] [-d domain] [-d domain] ...

The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By
default, it will attempt to use a webserver both for obtaining and installing
the cert. Major SUBCOMMANDS are:

  (default) run        Obtain & install a cert in your current webserver
  certonly             Obtain cert, but do not install it (aka "auth")
  install              Install a previously obtained cert in a server
  renew                Renew previously obtained certs that are near expiry
  revoke               Revoke a previously obtained certificate
  rollback             Rollback server configuration changes made during install
  config_changes       Show changes made to server config during installation
  plugins              Display information about installed plugins
letsencrypt: error: unrecognized arguments: --Host example.com --Port 22 --User user --WorkDir $HOME/public_html
```

**Comment by neurobin** [comment]
``` sh
lcget certonly -c ~/.neurobin/jssh/test.conf 
```

seems like you are passing jssh config file as letsencrypt config file. Quote from the doc:

> The following is an example which uses a letsencrypt configuration file (All outputs are shown):
> 
> ~$ lcget certonly -c neurobin.conf

where neurobin.conf is a letsencrypt config file (see the example in readme)

**You don't need to pass jssh config file, it will be automatically taken internally, just be sure to create the jssh config file with the actual domain name, e.g example.com.conf, www.example.com.conf etc...**

Clarified the doc by renaming the letsencrypt configuration file to a .ini extension file.

**Comment by baderj** [comment]
Yes of course, thank you! I got confused because right after creating the jssh <domain.conf> follows the call with the config file. The README is very good though, should have just continued reading to see the _other_ .conf file.
